import { Beat, LicenseOption, CategoryInfo, ServiceInfo } from "@/types";

export const LICENSE_OPTIONS: LicenseOption[] = [
  {
    id: "mp3",
    slug: "mp3",
    name: "Standard MP3",
    price: 29,
    format: "Untagged High-Quality MP3 (320kbps)",
    features: [
      "Untagged stereo audio file",
      "Up to 100,000 audio streams",
      "Distribution on Spotify & Apple Music",
      "1 Non-monetized music video",
    ],
  },
  {
    id: "wav",
    slug: "wav",
    name: "Premium WAV",
    price: 49,
    format: "Uncompressed 24-Bit Master WAV + MP3",
    features: [
      "Master studio WAV file (24-bit/48kHz)",
      "Up to 500,000 audio streams",
      "2 Commercial music videos",
      "Monetized YouTube streaming allowed",
    ],
    recommended: true,
  },
  {
    id: "stems",
    slug: "stems",
    name: "Trackout Stems",
    price: 99,
    format: "Separated Multitrack WAV Stems + Master WAV",
    features: [
      "All individual drum, synth, bass & vocal stems",
      "Perfect for professional studio mixing & vocal tuning",
      "Up to 1,000,000 audio streams",
      "Radio broadcasting rights included",
    ],
  },
  {
    id: "unlimited",
    slug: "unlimited",
    name: "Unlimited License",
    price: 199,
    format: "Full Master WAV + All Stems (No Caps)",
    features: [
      "Unlimited commercial audio streams",
      "Unlimited physical & digital sales",
      "Unlimited music videos & radio airplay",
      "For-profit live performance rights",
    ],
  },
  {
    id: "exclusive",
    slug: "exclusive",
    name: "Exclusive Rights",
    price: 499,
    format: "Full Ownership Transfer & Master Copyright",
    features: [
      "Sole ownership transferred directly to you",
      "Beat permanently removed from store",
      "Unlimited sync, streaming & physical distribution",
      "Official signed contract agreement",
    ],
  },
];

export const MOCK_BEATS: Beat[] = [
  {
    id: "beat_01",
    slug: "midnight-dynasty",
    title: "Midnight Dynasty",
    genre: "trap",
    mood: "Dark",
    bpm: 142,
    key: "Fm",
    duration: "3:04",
    price: 29,
    cover: "from-[#1d102e] via-[#121018] to-[#09080d]",
    featured: true,
    createdAt: "2026-03-10",
    tags: ["Travis Scott", "Cinematic", "Dark Synth", "Heavy 808"],
    pricing: { mp3: 29, wav: 49, stems: 99, unlimited: 199, exclusive: 499 },
  },
  {
    id: "beat_02",
    slug: "aura-latina",
    title: "Aura Latina",
    genre: "reggaeton",
    mood: "Melodic",
    bpm: 96,
    key: "Cm",
    duration: "2:48",
    price: 29,
    cover: "from-[#0f1d2e] via-[#10131a] to-[#09090d]",
    featured: true,
    createdAt: "2026-03-12",
    tags: ["Tainy", "Atmospheric", "Club", "Melodic"],
    pricing: { mp3: 29, wav: 49, stems: 99, unlimited: 199, exclusive: 499 },
  },
  {
    id: "beat_03",
    slug: "nocturnal-soul",
    title: "Nocturnal Soul",
    genre: "rnb",
    mood: "Soulful",
    bpm: 88,
    key: "Ebm",
    duration: "3:22",
    price: 29,
    cover: "from-[#1b1228] via-[#121018] to-[#09080d]",
    featured: true,
    createdAt: "2026-03-15",
    tags: ["Brent Faiyaz", "Vintage Rhodes", "Warm Bass", "Moody"],
    pricing: { mp3: 29, wav: 49, stems: 99, unlimited: 199, exclusive: 499 },
  },
  {
    id: "beat_04",
    slug: "sol-de-mar",
    title: "Sol de Mar",
    genre: "afrobeat",
    mood: "Chill",
    bpm: 104,
    key: "G",
    duration: "2:55",
    price: 29,
    cover: "from-[#241a10] via-[#161310] to-[#09080d]",
    featured: true,
    createdAt: "2026-03-16",
    tags: ["Burna Boy", "Percussive", "Organic", "Guitar"],
    pricing: { mp3: 29, wav: 49, stems: 99, unlimited: 199, exclusive: 499 },
  },
  {
    id: "beat_05",
    slug: "after-hours-echo",
    title: "After Hours Echo",
    genre: "house",
    mood: "Atmospheric",
    bpm: 126,
    key: "Am",
    duration: "3:40",
    price: 29,
    cover: "from-[#0d1e28] via-[#10141a] to-[#09090d]",
    featured: true,
    createdAt: "2026-03-17",
    tags: ["Kaytranada", "Deep Groove", "Synths", "Night"],
    pricing: { mp3: 29, wav: 49, stems: 99, unlimited: 199, exclusive: 499 },
  },
  {
    id: "beat_06",
    slug: "bronx-cathedral",
    title: "Bronx Cathedral",
    genre: "hiphop",
    mood: "Epic",
    bpm: 92,
    key: "Dm",
    duration: "3:15",
    price: 29,
    cover: "from-[#19152a] via-[#12111a] to-[#09080d]",
    featured: true,
    createdAt: "2026-03-18",
    tags: ["J. Cole", "Soul Sample", "Gritty Drums", "Storytelling"],
    pricing: { mp3: 29, wav: 49, stems: 99, unlimited: 199, exclusive: 499 },
  },
  {
    id: "beat_07",
    slug: "ghost-protocol",
    title: "Ghost Protocol",
    genre: "drill",
    mood: "Aggressive",
    bpm: 144,
    key: "Gm",
    duration: "2:39",
    price: 29,
    cover: "from-[#1d0e14] via-[#140f12] to-[#09080d]",
    featured: false,
    createdAt: "2026-03-19",
    tags: ["Central Cee", "Sliding 808", "Dark Piano", "OVO"],
    pricing: { mp3: 29, wav: 49, stems: 99, unlimited: 199, exclusive: 499 },
  },
  {
    id: "beat_08",
    slug: "velvet-horizon",
    title: "Velvet Horizon",
    genre: "rnb",
    mood: "Romantic",
    bpm: 82,
    key: "Bbm",
    duration: "3:18",
    price: 29,
    cover: "from-[#261528] via-[#16101c] to-[#09080d]",
    featured: false,
    createdAt: "2026-03-20",
    tags: ["The Weeknd", "80s Snare", "Lush Pad", "Emotional"],
    pricing: { mp3: 29, wav: 49, stems: 99, unlimited: 199, exclusive: 499 },
  },
  {
    id: "beat_09",
    slug: "fuego-eterno",
    title: "Fuego Eterno",
    genre: "reggaeton",
    mood: "Energetic",
    bpm: 98,
    key: "F#m",
    duration: "2:52",
    price: 29,
    cover: "from-[#101f2e] via-[#10141a] to-[#09090d]",
    featured: false,
    createdAt: "2026-03-21",
    tags: ["Bad Bunny", "Punchy Kick", "Vocal Chops", "Club"],
    pricing: { mp3: 29, wav: 49, stems: 99, unlimited: 199, exclusive: 499 },
  },
  {
    id: "beat_10",
    slug: "neon-syndicate",
    title: "Neon Syndicate",
    genre: "pop",
    mood: "Energetic",
    bpm: 120,
    key: "C",
    duration: "3:06",
    price: 29,
    cover: "from-[#1b2612] via-[#141910] to-[#09090d]",
    featured: false,
    createdAt: "2026-03-22",
    tags: ["Dua Lipa", "Disco Bass", "Modern Pop", "Bright"],
    pricing: { mp3: 29, wav: 49, stems: 99, unlimited: 199, exclusive: 499 },
  },
  {
    id: "beat_11",
    slug: "abyss-808",
    title: "Abyss 808",
    genre: "trap",
    mood: "Dark",
    bpm: 138,
    key: "C#m",
    duration: "2:44",
    price: 29,
    cover: "from-[#180f2c] via-[#120f1c] to-[#09080d]",
    featured: false,
    createdAt: "2026-03-23",
    tags: ["Metro Boomin", "Bells", "Dark Atmosphere", "Hard"],
    pricing: { mp3: 29, wav: 49, stems: 99, unlimited: 199, exclusive: 499 },
  },
  {
    id: "beat_12",
    slug: "savage-reign",
    title: "Savage Reign",
    genre: "drill",
    mood: "Aggressive",
    bpm: 142,
    key: "Em",
    duration: "2:58",
    price: 29,
    cover: "from-[#220d18] via-[#160f14] to-[#09080d]",
    featured: false,
    createdAt: "2026-03-24",
    tags: ["Pop Smoke", "Heavy Distortion", "Strings", "Grime"],
    pricing: { mp3: 29, wav: 49, stems: 99, unlimited: 199, exclusive: 499 },
  },
  {
    id: "beat_13",
    slug: "lagos-sunrise",
    title: "Lagos Sunrise",
    genre: "afrobeat",
    mood: "Melodic",
    bpm: 108,
    key: "D",
    duration: "3:11",
    price: 29,
    cover: "from-[#22180f] via-[#171410] to-[#09080d]",
    featured: false,
    createdAt: "2026-03-25",
    tags: ["Rema", "Acoustic Guitar", "Afro Swing", "Warm"],
    pricing: { mp3: 29, wav: 49, stems: 99, unlimited: 199, exclusive: 499 },
  },
  {
    id: "beat_14",
    slug: "golden-hour-dreams",
    title: "Golden Hour Dreams",
    genre: "pop",
    mood: "Atmospheric",
    bpm: 116,
    key: "A",
    duration: "3:24",
    price: 29,
    cover: "from-[#1f1910] via-[#151310] to-[#09080d]",
    featured: false,
    createdAt: "2026-03-26",
    tags: ["Billie Eilish", "Subtle Plucks", "Atmosphere", "Intimate"],
    pricing: { mp3: 29, wav: 49, stems: 99, unlimited: 199, exclusive: 499 },
  },
];

export const FEATURED_BEATS = MOCK_BEATS.slice(0, 6);

export const FLOW_CATEGORIES: CategoryInfo[] = [
  {
    id: "trap",
    title: "TRAP",
    tagline: "Cinematic tension, distorted low-end & cutting hi-hats",
    bpmRange: "130 – 160 BPM",
    count: 24,
    accentColor: "from-purple-600/30 to-zinc-950",
  },
  {
    id: "rnb",
    title: "R&B / SOUL",
    tagline: "Velvet chords, introspective night moods & vocal spaces",
    bpmRange: "75 – 105 BPM",
    count: 18,
    accentColor: "from-violet-700/30 to-zinc-950",
  },
  {
    id: "reggaeton",
    title: "REGGAETON",
    tagline: "Futuristic swing, dembow syncopation & urban club pulse",
    bpmRange: "90 – 102 BPM",
    count: 32,
    accentColor: "from-blue-600/30 to-zinc-950",
  },
  {
    id: "afrobeat",
    title: "AFRO",
    tagline: "Sun-soaked acoustic grooves, log drums & rhythmic swing",
    bpmRange: "100 – 116 BPM",
    count: 15,
    accentColor: "from-amber-600/20 to-zinc-950",
  },
  {
    id: "house",
    title: "HOUSE",
    tagline: "Hypnotic 4x4 pulses, rolling bass & late-night underground drive",
    bpmRange: "122 – 128 BPM",
    count: 12,
    accentColor: "from-cyan-600/25 to-zinc-950",
  },
  {
    id: "hiphop",
    title: "HIP-HOP",
    tagline: "Hard-hitting boom bap, soulful chops & organic rhythm textures",
    bpmRange: "84 – 98 BPM",
    count: 21,
    accentColor: "from-indigo-600/30 to-zinc-950",
  },
];

export const STUDIO_SERVICES: ServiceInfo[] = [
  {
    id: "custom-production",
    title: "Music Production",
    category: "Full Production",
    description: "Tailored full-scale record production from scratch designed strictly around your vocal texture, artistic vision, and delivery.",
    turnaround: "5-7 business days",
    startingPrice: "$350",
    features: [
      "Original melody & drum composition",
      "Full multitrack stems (WAV 24-bit)",
      "Arrangement consulting & revisions",
      "Commercial release rights",
    ],
  },
  {
    id: "mixing-mastering",
    title: "Mixing & Mastering",
    category: "Post-Production",
    description: "Industry-grade sonic engineering that provides three-dimensional separation, punch, vocal presence, and streaming platform loudness.",
    turnaround: "3-5 business days",
    startingPrice: "$180",
    features: [
      "Precision vocal tuning & alignment",
      "Analog-modeled spatial depth & EQ",
      "Spotify & Apple Music loudness compliance",
      "Includes instrumental & acapella passes",
    ],
  },
  {
    id: "artist-development",
    title: "Artist Development",
    category: "Mentorship & Strategy",
    description: "One-on-one executive creative direction to identify your sonic pocket, curate cohesive EP tracklists, and elevate your market profile.",
    turnaround: "Monthly program",
    startingPrice: "$600 / mo",
    features: [
      "Weekly private strategic sessions",
      "Full catalog audit & feedback",
      "Priority production access",
      "Direct release readiness roadmap",
    ],
  },
  {
    id: "custom-sound-design",
    title: "Custom Production",
    category: "Exclusive Projects",
    description: "Specialized scoring, sync licensing beds, and unique sound design for ad campaigns, short films, and high-impact branded media.",
    turnaround: "Custom timeline",
    startingPrice: "$500",
    features: [
      "Bespoke sound design & Foley",
      "Direct stem delivery with cue sheets",
      "Unlimited sync & broadcast rights",
      "Expedited milestone delivery",
    ],
  },
];
